name: tags-test

env:
  version: 3.1.4

on:
  release:
    types:
      - published

jobs:

  check-tag:
    runs-on: ubuntu-latest
    steps:
      - name: check tag ${{ github.ref }}
        run: |
          echo "version is: ${{ env.version }}"
          echo "checking for release tag:"
          if [[ ${{ github.ref }} =~ ^refs\/tags\/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "found release tag ${{ github.ref }}"
            exit 0
          else
            echo "did not find release tag. Ref was ${{ github.ref }}. Exiting"
            exit 1
          fi

  test-tag:
    needs: check-tag
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: [2.7, 3.7, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run test script
        run: python test.py
      - run: |
          echo "FYI: version is: ${{ env.version }}"
          env | sort

  deploy-tag:
    needs: test-tag
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo "deploying tag"
          echo "FYI: version is: ${{ env.version }}"
